# Generated by Django 3.2.2 on 2021-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('qr_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=600)),
                ('qr_codes', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
